name: PlayerParticles
main: dev.esophose.playerparticles.PlayerParticles
version: '@version@'
api-version: '1.13'
description: Display particles around your player and blocks using customized styles and data!
author: Esophose
website: https://www.spigotmc.org/resources/playerparticles.40261/
softdepend: [PlaceholderAPI, WorldGuard, WorldEdit]
commands:
  pp:
    description: The main PlayerParticles command. By default, opens the GUI.
  ppo:
    description: Allows executing a /pp command for another player.
